import {test,expect} from "@playwright/test";
const password=process.env.ROLE_FIXTURE_PASSWORD;
async function openExec(browser,viewport={width:1440,height:960}){const context=await browser.newContext({viewport});const page=await context.newPage();await page.goto("/");await page.getByPlaceholder("Work email").fill("exec@ceac.local.test");await page.getByPlaceholder("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page.locator(".executive-app")).toBeVisible({timeout:15000});return{context,page};}
test.describe("Premium redesign R4 Executive",()=>{
 test("Executive Overview is a visual leadership briefing",async({browser})=>{const{context,page}=await openExec(browser);await expect(page.locator(".executive-command-surface")).toBeVisible();await expect(page.getByRole("heading",{name:"Ministry overview",exact:true})).toBeVisible();await page.screenshot({path:"test-artifacts/redesign-r4-executive-overview.png",fullPage:true});await context.close();});
 test("Executive Work prioritises delegated work and decisions",async({browser})=>{const{context,page}=await openExec(browser);await page.locator(".premium-side").getByRole("button",{name:"Work",exact:true}).click();await expect(page.getByRole("heading",{name:"Work",exact:true})).toBeVisible();for(const label of ["Given out","Needs review","Mine"])await expect(page.getByRole("tab",{name:new RegExp(label)})).toBeVisible();await page.screenshot({path:"test-artifacts/redesign-r4-executive-work.png",fullPage:true});await context.close();});
 test("Executive shell uses Ministry Portfolio Organisation Finance Reports",async({browser})=>{const{context,page}=await openExec(browser);for(const label of ["Ministry","Portfolio","Organisation","Finance","Reports"])await expect(page.locator(".premium-side").getByRole("button",{name:label,exact:true})).toBeVisible();await expect(page.locator(".premium-side").getByRole("button",{name:"Strategy",exact:true})).toHaveCount(0);await page.locator(".premium-side").getByRole("button",{name:"Ministry",exact:true}).click();await expect(page.getByRole("heading",{name:"Ministry",exact:true})).toBeVisible();await page.locator(".premium-side").getByRole("button",{name:"Portfolio",exact:true}).click();await expect(page.getByRole("heading",{name:"Portfolio",exact:true})).toBeVisible();await context.close();});
 test("Executive Organisation is read-only leadership context",async({browser})=>{const{context,page}=await openExec(browser);await page.locator(".premium-side").getByRole("button",{name:"Organisation",exact:true}).click();await expect(page.getByRole("heading",{name:"Organisation",exact:true})).toBeVisible();await expect(page.getByText(/Administration remains responsible/)).toBeVisible();await page.screenshot({path:"test-artifacts/redesign-r4-executive-organisation.png",fullPage:true});await context.close();});
 test("Executive Finance stays contextual and exposes only required Group Pastor decisions",async({browser})=>{const{context,page}=await openExec(browser);await page.locator(".premium-side").getByRole("button",{name:"Finance",exact:true}).click();await expect(page.getByRole("heading",{name:"Finance",exact:true})).toBeVisible();await expect(page.getByText(/Requests that specifically require Group Pastor authority appear below/)).toBeVisible();await expect(page.getByText("Requests needing Group Pastor",{exact:true})).toBeVisible();await expect(page.getByText("Could not load Finance",{exact:true})).toHaveCount(0);await page.screenshot({path:"test-artifacts/redesign-r4-executive-finance.png",fullPage:true});await context.close();});
 test("Executive mobile remains within viewport",async({browser})=>{const{context,page}=await openExec(browser,{width:390,height:844});await expect(page.locator(".premium-tabs")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:"test-artifacts/redesign-r4-executive-mobile.png",fullPage:true});await context.close();});
});