import { useEffect,useState } from "react";
import { supabase } from "../lib/supabase";
import { LoadingState,ProductNotice,ProgressMeter } from "../components/bits";
import { humanError } from "../lib/productLanguage";
export default function ExecutiveReports({me}){
 const [period,setPeriod]=useState(null),[reports,setReports]=useState([]),[units,setUnits]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null);
 useEffect(()=>{load();},[me.org_id]);
 async function load(){setLoading(true);setError(null);try{const [p,u]=await Promise.all([supabase.from("report_periods").select("id,label,status,starts_on,ends_on").eq("org_id",me.org_id).order("starts_on",{ascending:false}).limit(1).maybeSingle(),supabase.from("units").select("id,name").eq("org_id",me.org_id).eq("active",true).order("name")]);if(p.error||u.error)throw p.error||u.error;setPeriod(p.data||null);setUnits(u.data||[]);if(p.data){const r=await supabase.from("reports").select("unit_id,status,version,submitted_at").eq("period_id",p.data.id).eq("scope","unit");if(r.error)throw r.error;const latest={};(r.data||[]).forEach(x=>{if(!latest[x.unit_id]||Number(x.version)>Number(latest[x.unit_id].version))latest[x.unit_id]=x});setReports(Object.values(latest));}}catch(e){setError(humanError(e,"Reports could not be loaded."));}finally{setLoading(false);}}
 const filed=reports.filter(x=>x.status!=="draft").length;
 return <div className="body premium-exec-page"><header className="exec-page-head"><div><span className="eyebrow">Leadership reporting</span><h1 className="h1">Reports</h1><p className="screen-note">Reporting coverage and the units still outstanding. Administration controls periods and report configuration.</p></div></header>
 {error&&<ProductNotice tone="error" title="Could not load Reports">{error}</ProductNotice>}{loading?<LoadingState label="Loading reports…"/>:period?<><section className="exec-report-hero"><span>Current period</span><strong>{period.label}</strong><ProgressMeter value={filed} max={units.length} label="Reports filed" detail={filed+" of "+units.length+" units"}/></section><section className="exec-list">{units.map(u=>{const r=reports.find(x=>x.unit_id===u.id);return <div className="exec-report-row" key={u.id}><span><strong>{u.name}</strong><small>{r?.submitted_at?new Date(r.submitted_at).toLocaleDateString("en-GB"):"No submitted report recorded"}</small></span><b className={r&&r.status!=="draft"?"ok":""}>{r&&r.status!=="draft"?"Filed":"Waiting"}</b></div>})}</section></>:<div className="premium-empty">No reporting period is recorded.</div>}</div>;
}